ACTION: action
DEFAULT_IP_ADDRESS: 127.0.0.1
DEFAULT_PORT: 7777
ENCODING: utf-8
ERROR: error
MAX_CONNECTIONS: 5
MAX_PACKAGE_LENGTH: 1024
PRESENCE: false
RESPONSE: false
TIME: time
TYPE: status
USER:
  ACCOUNT_NAME: account_name
  STATUS: status
